package day_38_StaticKeyWord.ScrumTasks;

import com.sun.xml.internal.bind.v2.model.core.ID;

public class Tester {

    public String name, ID, jobTitle, companyName;
    public double salary;
    public char gender;

    // no static given because there isn't a consistent variable so theres no need for static attribute

    // setInfo generated by constructor (alt+ins then click constructor, then select all options then hit enter and this will be generated
    // after it is generated, set return type to void and change name to setInfo
    public void setInfo(String name, String ID, String jobTitle, String companyName, double salary, char gender) {
        this.name = name;
        this.ID = ID;
        this.jobTitle = jobTitle;
        this.companyName = companyName;
        this.salary = salary;
        this.gender = gender;
    }

    public void smokeTesting(){
        System.out.println(name+" is performing smoke testing");
    }

    public void creatingTicket(){
        System.out.println(name+" is creating ticket");
    }

    // toString generated by constructor
    public String toString() {
        return "Tester{" +
                "name='" + name + '\'' +
                ", ID='" + ID + '\'' +
                ", jobTitle='" + jobTitle + '\'' +
                ", companyName='" + companyName + '\'' +
                ", salary=" + salary +
                ", gender=" + gender +
                '}';
    }
}
/*
create a class called Tester
					Attributes:
						name, employeeID, JobTitle, Salary
					Actions:
						setInfo(), smokeTesting(),  creatingTicket(), toString()
 */